### PR TITLE
RFC6062 TURN TCP allocations

### LINKED ISSUE #143: RFC6062 implementation
I've read #118 and the associated branch [`rfc-6062-client`](https://github.com/pion/turn/tree/rfc-6062-client) and decided starting from scratch would be a better for me.

Currently on branch [`rfc6062`](https://github.com/pion/turn/tree/rfc6062) (sorry for confusing naming)  is a partially done modification of the client. Creating outbound requests `Connect` works as well as well as associating data connections `ConnectionBind`. Tested manually with `coturn`.

## Changes
`internal/proto`:
- add `ProtoTCP` 

`turn`:
- add `ProtoTCP` and `ProtoUDP`
- add `ConnectionID` type to main package
- add `ClientConfig.TransportProtocol`
- add `Client.transportProtocol`
- add `Client.nonce`
- add `Client.Connect()`
- add `Client.ConnectionBind()`

## Questions

- what kind of tests to add?
- successful authentication method should probably be stored (need to be reused)?
- `Client.Allocate` returns a `net.PacketConn`, not sure how that fits into TCP?
- the server will send `ConnectionAttempt` indications to the client for receiving connections, how should this be exposed to users? (also needs `CreatePermission`)
- handling refreshes

## example client

```go
package main

import (
	"fmt"
	"log"
	"net"

	"github.com/pion/turn/v2"
)

func main() {
	// Dial TURN Server
	turnServerAddr := "1.2.3.4:3478"
	conn, err := net.Dial("tcp", turnServerAddr)
	if err != nil {
		panic(err)
	}

	// Start a new TURN Client and wrap our net.Conn in a STUNConn
	// This allows us to simulate datagram based communication over a net.Conn
	cfg := &turn.ClientConfig{
		STUNServerAddr: turnServerAddr,
		TURNServerAddr: turnServerAddr,
		Conn:           turn.NewSTUNConn(conn),
		Username:       "user",
		Password:       "pass",
		TransportProtocol:       turn.ProtoTCP,
	}

	client, err := turn.NewClient(cfg)
	if err != nil {
		panic(err)
	}
	defer client.Close()

	// Start listening on the conn provided.
	err = client.Listen()
	if err != nil {
		panic(err)
	}

       // not sure what to do with relayConn
	relayConn, err := client.Allocate()
	if err != nil {
		panic(err)
	}
	defer func() {
		if closeErr := relayConn.Close(); closeErr != nil {
			panic(closeErr)
		}
	}()
	log.Printf("relayed-address=%s", relayConn.LocalAddr().String())

        // peer address to connect to
	ta, _ := net.ResolveTCPAddr("tcp4", "145.100.104.117:8888")

        // attempt connection, get connection id
	cid, err := client.Connect(ta)
	if err != nil {
		panic(err)
	}

        // open new data connection to turn server
	dconn, err := net.Dial("tcp", turnServerAddr)
	if err != nil {
		panic(err)
	}

        // associate connection with connection id
	err = client.ConnectionBind(dconn, cid)
	if err != nil {
		panic(err)
	}

       // use connection
	_, err = dconn.Write([]byte("hello world"))
	if err != nil {
		panic(err)
	}

	buf := make([]byte, 1024)
	n, err := dconn.Read(buf)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(buf[:n]))
}
```

### PR DESCRIPTION
**Pull request by seankhliao**
#### Description

Implements both client and server side support for TCP allocations and connections to peers.

Things to do:
- [ ] tests, what to test?
- [ ] add example(s)
- [ ] review/break out use of syscalls for port reuse
- [ ] review double lookup `internal/server/turn.go`

#### Reference issue

Fixes #143, #118

### CODE REVIEW

**Comment by JarnoVgr** [comment]
Great to see you've added this! I'll definitely test this within a couple of weeks.

(- Ywat from reddit)

**Comment by Sean-Der** [comment]
This is amazing! Nice work @seankhliao I am reviewing now :) 

I don't have access to a computer for another day or two so will be slower then usual sorry :(

**Comment by kylecarbs** [comment]
@Sean-Der is there anything I can do to help this get merged? 🙌

**Comment by GingerAdonis** [comment]
@Sean-Der Did you get around testing these changes?

**Comment by GingerAdonis** [comment]
Bump. This is a highly useful PR.

**Comment by seankhliao** [comment]
I'm going to close this as:

1. I've lost all context for this 
2. the underlying codebase seems to changed quite a bit

If anyone wants to work on this, feel free to base it off this code (if it's still useful)

**Pull request closed without merging**
