### PR TITLE
Add IPv6 ClientConfig flag

### PR DESCRIPTION
**Pull request by hetelek**
Adds a `IPv6` flag to the turn.ClientConfig, which will allow for IPv6 relay support.

https://github.com/pion/ice/pull/462

### CODE REVIEW

**Comment by Sean-Der** [comment]
@jech

**Comment by jech** [comment]
@hetelek could you please explain why this is needed?  Why is it not enough to infer the address family from ClientConfig.Conn, using something like:

   nework := config.Conn.LocalAddr().Network()

This would avoid adding a new API, and would give us more flexibility in the future if we decide that this is not the right approach.

If an explicit field is needed, I'd prefer it to be called `Network` and to be either a string or an int rather than a simple boolean, in case more values are needed in the future.

**Comment by stv0g** [comment]
This PR gets obsoleted if #276 gets merged.

**Comment by stv0g** [comment]
#276 has been merged. I therefore close this PR.

**Pull request closed without merging**
