### PR TITLE
Add initial draft of FAQ

### PR DESCRIPTION
**Pull request by jipson7**
#### Description

Added FAQ.md to repo root with some initial questions.

@Sean-Der If there is an existing FAQ I can merge this with, or a better place for it to live, please let me know and I'll change it. Thanks again for the help.

### CODE REVIEW

**Comment by Sean-Der** [comment]
Amazing! This LGTM @jipson7 

Mind adding yourself to the README and then CI will pass?

**Comment by Sean-Der** [comment]
You can run the checks locally by doing the following. You can see everything we run in the `.travis.yml`

```
bash .github/lint-commit-message.sh
bash .github/assert-contributors.sh
```

**Comment by jipson7** [comment]
@Sean-Der got it. Ill add more that I come across.

**Review by stv0g — APPROVED** [review]
Thanks @jipson7

**Pull request merged**
