### PR TITLE
fix: update nonce in refreshPermissions when refresh is 438

### PR DESCRIPTION
**Pull request by AeroNotix**
Relates: #102 

cc @enobufs

### CODE REVIEW

**Comment by AeroNotix** [comment]
Build failed because of `The command "bash .github/lint-commit-message.sh" exited with 1.` All worthwhile tests pass, however.

**Comment by Sean-Der** [comment]
@AeroNotix thanks for grabbing this!

CI should be green if
* Add yourself to the README
* Keep your subject to 50 chars `fix: handle stale nonce in refreshPermissions`  you can fill out the body more, could be helpful for others in the future.

**Comment by AeroNotix** [comment]
@enobufs yes this does fix the issue for me.

Here's how I tested:

* Two applications, one with and one without the code in the PR. 
* I brokered a connection between the two peers and waited 12 minutes.
    * 12 minutes because _by default_ (per RFC) the nonce value is valid for 10 minutes, we then have a timer on 120 seconds which calls CreatePermissions. To me I believe this makes the timing of the 438 line up to when the server has invalidated the nonce value.
* Once the 12 minutes was up, I ensured to check logs. In the peer without the change, the CreatePermissions 438 error happened regularly in the logs.
* Once the 12 minutes was up, in the peer _with_ the changes the logs were free from the CreatePermissions 438 error.

I believe, for my _particular_ use-case this PR fixes the issue but reading through the code more and more and starting to understand the RFC for how the Nonce should/could be used I believe a more general way to update the nonce could be implemented.

**Comment by enobufs** [comment]
(I really don't like this commit-message checker...)
`git rebase master -i` should help you modifying the commit message...

```
* Separate subject from body with a blank line
* Limit the subject line to 50 characters
* Capitalize the subject line
* Do not end the subject line with a period
* Wrap the body at 72 characters
```

**Comment by AeroNotix** [comment]
@enobufs now the linter is happy now

**Comment by enobufs** [comment]
@AeroNotix Great work! Thank you!

**Pull request merged**
