### PR TITLE
stun message pointer nil error

### PR DESCRIPTION
**Pull request by hcm007**
github.com/pion/turn/internal/client.(*UDPConn).bind(0xc080582000, 0xc05ecd7f80, 0x434fd6, 0x8f2a98)
    /go/pkg/mod/github.com/pion/turn@v1.3.5/internal/client/conn.go:521 +0x45f
github.com/pion/turn/internal/client.(*UDPConn).WriteTo.func2.1(0xc080582000, 0xc05ecd7f80)
    /go/pkg/mod/github.com/pion/turn@v1.3.5/internal/client/conn.go:217 +0x39
created by github.com/pion/turn/internal/client.(*UDPConn).WriteTo.func2
    /go/pkg/mod/github.com/pion/turn@v1.3.5/internal/client/conn.go:216 +0xad

#### Reference issue
Fixes #...

### CODE REVIEW

**Comment by hcm007** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x73fe6f]
goroutine 5133193 [running]:
github.com/pion/turn/internal/client.(*UDPConn).bind(0xc080582000, 0xc05ecd7f80, 0x434fd6, 0x8f2a98)
    /go/pkg/mod/github.com/pion/turn@v1.3.5/internal/client/conn.go:521 +0x45f
github.com/pion/turn/internal/client.(*UDPConn).WriteTo.func2.1(0xc080582000, 0xc05ecd7f80)
    /go/pkg/mod/github.com/pion/turn@v1.3.5/internal/client/conn.go:217 +0x39
created by github.com/pion/turn/internal/client.(*UDPConn).WriteTo.func2
    /go/pkg/mod/github.com/pion/turn@v1.3.5/internal/client/conn.go:216 +0xad

**Comment by enobufs** [comment]
@hcm007 Thanks for your PR.

There was a similar PR earlier we addressed it.
Your issue might have already been fix at 0e40b1c.

You could use `replace` in go.mod to confirm, but we should tag the current master then incorporated it into pion/webrtc soon.

**Comment by enobufs** [comment]
once #97 is merged, I will tag, then we can bump pion/turn version for pion/webrtc.

**Comment by enobufs** [comment]
Hi @hcm007, the fix pion/turn@0e40b1c has been landed in pion/webrtc@cabbd8b.

**Comment by Sean-Der** [comment]
Fixed with https://github.com/pion/webrtc/commit/cabbd8b

**Pull request closed without merging**
